Databases week2
Lokesh-sw/hyf-homework pull request #16
Opened 2022-08-25 17:06 UTC by Lokesh-sw

2022-08-25 22:01 UTC, Elia-Git requested changes
HI Lokesh,

Pls pay attention on your fromating your code as you are using extremely many(unwanted) lines and explore about JOIN .
Join tool: https://www.w3schools.com/sql/sql_join.asp
Code formatter: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

2022-08-25 22:01 UTC, Elia-Git commented on databases/week2/homework_create_database.sql
> +    );
good here!

2022-08-25 22:01 UTC, Elia-Git commented on databases/week2/homework_additionalqueries.sql
> +
Small fix to differentiate months and tasks 
```
SELECT
  monthname(task.created) as month, COUNT(task.id) as task_total
FROM
  task
GROUP BY month;
```

2022-08-25 22:01 UTC, Elia-Git commented on databases/week2/homework_additionalqueries.sql
> +    user.name = "Maryrose Meadows" AND month(created) = 9;
How are you joining tables task and user here..There should be something common (most of the time id) to join to different tables.

See below
```
SELECT user.name, task.title, task.created
FROM task
JOIN user_task ON task.id = user_task.task_id
JOIN user  ON user.id = user_task.user_id
WHERE user.name LIKE 'Maryrose Meadows' AND MONTH(created)=09;
```

2022-08-25 22:01 UTC, Elia-Git commented on databases/week2/homework_additionalqueries.sql
> +	user.name LIKE "%Donald Duck%" AND task.status_id = 1;
Here also tables task and user are actually not joining.

2022-08-25 22:01 UTC, Elia-Git commented on databases/week2/homework_additionalqueries.sql
> +
Pls, read something about how the join tool works!
https://www.w3schools.com/sql/sql_join.asp

2022-08-25 22:01 UTC, Elia-Git commented on databases/week2/homework_excercise2.sql
> +;
Good here!

2022-08-29 19:02 UTC, Lokesh-sw commented
> HI Lokesh,
> 
> Pls pay attention on your fromating your code as you are using extremely many(unwanted) lines and explore about JOIN . Join tool: https://www.w3schools.com/sql/sql_join.asp Code formatter: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

2022-08-29 19:04 UTC, Lokesh-sw commented on databases/week2/homework_excercise2.sql
> +;
@Elia-Git  Thank you for your constructive feed back. I have made changes and learning more about join tool.

2022-08-31 17:53 UTC, Lokesh-sw commented on databases/week2/homework_additionalqueries.sql
> +    user.name = "Maryrose Meadows" AND month(created) = 9;
query solution you provided didnt work and trown error. could this be an alternative solution

```sql
SELECT task.title, task.created, user.name
FROM task 
JOIN user ON user.id = task.user_id
WHERE user.name LIKE 'Maryrose Meadows' AND MONTH(created)=09;
```

2022-08-31 18:09 UTC, Lokesh-sw commented on databases/week2/homework_additionalqueries.sql
> +	user.name LIKE "%Donald Duck%" AND task.status_id = 1;
On this query could the following solution work?

```sql
SELECT 
	task.title, task.status_id, user.name, status.name
 FROM
	task
 JOIN 
	user ON user.id = task.user_id
JOIN 
status ON status.id = task.status_id
WHERE user.name LIKE "Donald Duck" AND status.name = 'Not started';
```

2022-09-09 15:46 UTC, merged